class AddFieldsToGames < ActiveRecord::Migration[5.0]
  def change
    add_column :games, :attr1, :string #this is a stub...
    add_column :games, :attr1, :string #this is a stub...
    add_column :games, :attr1, :string #this is a stub...
  end
end
